// USERS PERMISSIONS
export const CREATE_USER = 'CREATE_USER';
export const READ_USER = 'READ_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
// DOCUMENTS PERMISSIONS
export const CREATE_DOCUMENTS = 'CREATE_DOCUMENTS';
export const READ_DOCUMENTS = 'READ_DOCUMENTS';
export const UPDATE_DOCUMENTS = 'UPDATE_DOCUMENTS';
export const DELETE_DOCUMENTS = 'DELETE_DOCUMENTS';
export const SHARE_DOCUMENTS = 'SHARE_DOCUMENTS';
// ROLES PERMISSIONS
export const CREATE_ROLES = 'CREATE_ROLES';
export const READ_ROLES = 'READ_ROLES';
export const UPDATE_ROLES = 'UPDATE_ROLES';
export const DELETE_ROLES = 'DELETE_ROLES';
